apiVersion: apps/v1
kind: Deployment
metadata:
  name: addressbook-ui-2
  namespace: openshift-gitops
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: addressbook-ui-2
  template:
    metadata:
      labels:
        app: addressbook-ui-2
    spec:
      containers:
      - image: quay.io/argoprojlabs/argocd-e2e-container:0.2
        name: addressbook-ui-2
        ports:
        - containerPort: 80
