apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
    spec:
      containers:
      - image: gcr.io/heptio-images/ks-guestbook-demo:0.2
        name: guestbook-ui
        resources:
          limits:
            memory: "200Mi"
          requests:
            memory: "150Mi"
        ports:
        - containerPort: 80
      - image: gcr.io/heptio-images/ks-guestbook-demo:0.2
        name: guestbook-ui2
        resources:
          limits:
            memory: "100Mi"
          requests:
            memory: "50Mi"
        ports:
        - containerPort: 81
